"""Generate under activation steering across a lambda grid.

One model, one direction, many lambdas. Positive lambda on the IT checkpoint pushes it
toward DPO behaviour; negative lambda on the DPO checkpoint pushes it back. Run the
script twice, once per side, to get both arms.

    python scripts/steer_sweep.py --model-config configs/tulu3.yaml \
        --eval-config configs/steer_sweep.yaml --side it

Writes one JSONL per lambda plus an unsteered baseline for that side. Resume is by
(lambda, prompt id): a lambda whose file already holds every prompt is skipped, and a
partial file is topped up. Scoring is a separate step -- this produces text only, so it
needs no judge server.

Note the baseline is generated by the same code path with the hooks inactive rather
than by a separate branch, so any difference between baseline and lambda=0 would be a
bug rather than a finding.
"""

from __future__ import annotations

import argparse
import gc
import json
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from steering import activation_artifact
from steering.artifacts import GpuMonitor, sync_to_hub, write_run_metadata
from steering.config import ModelConfig
from steering.data import (
    VALID_HARMFULQA_PARTITIONS,
    load_advbench_evaluation,
    load_harmfulqa_partition,
    load_hh_rlhf_evaluation,
)
from steering.endpoint_binding import resolve_model_source
from steering.generate import build_chat_prompts, generate_batched, suggest_batch_size
from steering.models import load_model, load_tokenizer
from steering.splits import load_manifest, validate_manifest_identity
from steering.steer import ActivationSteering, build_vectors, random_vectors_like, steered_layers
from steering.utils import append_jsonl, load_yaml, read_jsonl, set_all_seeds, setup_logging

HARMFULQA_SWEEP_PARTITIONS = ("development", "calibration")


#: Frozen primary steering protocol (Task 014). An endpoint-backed run is only
#: protocol_profile="primary_v1" when its resolved configuration matches every one of
#: these exactly -- see classify_protocol_profile below. Kept as the single source of
#: truth: SteerSweepConfig's own defaults are built from these same constants, so the
#: dataclass defaults and configs/steer_sweep.yaml cannot silently drift apart.
PRIMARY_COEFFICIENTS: Tuple[float, ...] = (0.01, 0.025, 0.05, 0.075, 0.10)
PRIMARY_LAYERS: Tuple[int, ...] = (27, 28, 29, 30, 31)
PRIMARY_VECTOR_METHOD = "mean"
PRIMARY_VECTOR_NORMALISE = "relative"
PRIMARY_POSITIONS = "all"
PRIMARY_PRESERVE_NORM = False
PRIMARY_MAX_NEW_TOKENS = 512
PRIMARY_MAX_INPUT_LENGTH = 2048
PRIMARY_HARMFULQA_PARTITION = "calibration"
PRIMARY_LAYERS_LAST_K = 5

#: The only seeds a matched random-direction control may use (protocol Section 8).
RANDOM_CONTROL_SEEDS: Tuple[int, ...] = (11, 22, 33, 44, 55)

#: The only layers a single-layer diagnostic may evaluate (protocol Section 6: "A
#: compact single-layer diagnostic may evaluate layers 11, 19, 27, 31").
DIAGNOSTIC_LAYERS: Tuple[int, ...] = (11, 19, 27, 31)

#: A full projection removal uses exactly one coefficient, 1.0 -- the primary grid
#: (PRIMARY_COEFFICIENTS) sweeps installation/reversal strength and is not itself the
#: predeclared ablation diagnostic.
ABLATION_LAMBDAS: Tuple[float, ...] = (1.0,)

#: Every label a run's metadata may carry -- exactly one, never inferred by omission.
PROTOCOL_PROFILES: Tuple[str, ...] = (
    "primary_v1", "secondary_random_control_v1", "secondary_ablation_v1",
    "secondary_layer_diagnostic_v1", "legacy_nonconfirmatory",
)


@dataclass
class SteerSweepConfig:
    """Settings for one direction of a steering sweep."""

    # Prompts
    prompt_source: str = "harmfulqa"       # harmfulqa | advbench | hh_rlhf

    # Frozen manifest partition, when prompt_source == "harmfulqa". Only "development"
    # or "calibration" are allowed here -- construction is direction-estimation data,
    # and final_evaluation is reserved for the later confirmatory runner. A CLI
    # --partition, if given, overrides this. "calibration" is the frozen primary
    # protocol's default evaluation partition (Task 014). Must be explicitly null when
    # prompt_source is "hh_rlhf" or "advbench" (Task 019) -- those frozen evaluation
    # panels are not partitioned by manifest and never accept a HarmfulQA partition.
    prompt_partition: Optional[str] = PRIMARY_HARMFULQA_PARTITION

    # Not consulted when prompt_source == "harmfulqa": the named partition is loaded in
    # full, with no sampling. For prompt_source in {"hh_rlhf", "advbench"} (Task 019),
    # the complete frozen evaluation panel is always loaded in full, and n_prompts must
    # equal its exact record count -- an assertion on the panel size, not a sample size.
    n_prompts: int = 300

    # Frozen primary coefficients (Task 014), given as magnitudes; the sign comes from
    # --side.
    lambdas: Sequence[float] = field(default_factory=lambda: list(PRIMARY_COEFFICIENTS))

    # Which layers, counted from the top. layers_last_k=5 on a 32-layer checkpoint
    # (both frozen pairs) resolves to the frozen primary layer set PRIMARY_LAYERS.
    layers_last_k: int = PRIMARY_LAYERS_LAST_K

    # Vector construction. "mean" is the frozen primary direction (Eq. 2); "pc3" is
    # what the v1 notebook ran -- never labelled primary_v1.
    vector_method: str = PRIMARY_VECTOR_METHOD
    vector_normalise: Optional[str] = PRIMARY_VECTOR_NORMALISE   # None | unit | relative
    positions: str = PRIMARY_POSITIONS                            # all | new
    preserve_norm: bool = PRIMARY_PRESERVE_NORM

    # Where the activations for vector construction live -- must agree with
    # layer_profile.py's own LayerProfileConfig.output_dir default, since both name the
    # same manifest-backed construction tree (<activations_dir>/<model>/construction/).
    activations_dir: str = "outputs/layer_profile"

    # Generation
    max_new_tokens: int = PRIMARY_MAX_NEW_TOKENS
    batch_size: Optional[int] = None         # None -> size from free VRAM
    max_input_length: int = PRIMARY_MAX_INPUT_LENGTH

    output_dir: str = "outputs/steer"

    @classmethod
    def from_yaml(cls, path: Union[str, Path]) -> "SteerSweepConfig":
        return cls(**load_yaml(path))


# Protocol-profile classification (Task 014)
#
# Every run gets exactly one label. Rather than a general experiment-management
# framework, this is a single pure function over the resolved facts a run already has
# before any prompt, vector, model, or GPU access -- so it can run first and raise
# before any of that, and so "ambiguous" is a real, reachable outcome rather than a
# silently-picked default.


class ProtocolProfileError(ValueError):
    """An endpoint-backed steering-sweep run's resolved configuration does not match
    any of the five declared protocol profiles."""


@dataclass
class RunProfileInputs:
    """The resolved facts a steering-sweep run's protocol-profile classification
    depends on -- config values plus CLI flags, all available before any prompt,
    vector, model, or GPU access.

    `random_seed` is the dedicated `--random-seed` random-direction identity, never
    the general `--seed` run seed -- the two are independent (see
    validate_random_seed_args).
    """

    endpoint_backed: bool
    lambdas: Sequence[float]
    layers: Sequence[int]
    vector_method: str
    vector_normalise: Optional[str]
    positions: str
    preserve_norm: bool
    max_new_tokens: int
    max_input_length: int
    mode: str
    random_control: bool
    random_seed: Optional[int]
    external_vectors: bool
    single_layer_override: bool


def _matches_frozen_primary_core(inputs: RunProfileInputs) -> bool:
    """Every frozen-protocol field a `primary_v1` run must match exactly, and that a
    `secondary_random_control_v1` run must "otherwise preserve" (protocol Section 8) --
    everything about the primary intervention except which direction is used."""
    return (
        tuple(inputs.lambdas) == PRIMARY_COEFFICIENTS
        and tuple(inputs.layers) == PRIMARY_LAYERS
        and inputs.vector_method == PRIMARY_VECTOR_METHOD
        and inputs.vector_normalise == PRIMARY_VECTOR_NORMALISE
        and inputs.positions == PRIMARY_POSITIONS
        and inputs.preserve_norm == PRIMARY_PRESERVE_NORM
        and inputs.max_new_tokens == PRIMARY_MAX_NEW_TOKENS
        and inputs.max_input_length == PRIMARY_MAX_INPUT_LENGTH
    )


def _matches_frozen_settings_except_layers(inputs: RunProfileInputs) -> bool:
    """Everything `_matches_frozen_primary_core` checks except the layer set itself --
    what a `secondary_layer_diagnostic_v1` run (a single, different, predeclared
    layer) must still match."""
    return (
        tuple(inputs.lambdas) == PRIMARY_COEFFICIENTS
        and inputs.vector_method == PRIMARY_VECTOR_METHOD
        and inputs.vector_normalise == PRIMARY_VECTOR_NORMALISE
        and inputs.positions == PRIMARY_POSITIONS
        and inputs.preserve_norm == PRIMARY_PRESERVE_NORM
        and inputs.max_new_tokens == PRIMARY_MAX_NEW_TOKENS
        and inputs.max_input_length == PRIMARY_MAX_INPUT_LENGTH
    )


def _matches_frozen_ablation_core(inputs: RunProfileInputs) -> bool:
    """What a `secondary_ablation_v1` run must match: the frozen primary layer set,
    vector method/normalisation, positions, preserve_norm, and generation limits --
    but exactly the single full-removal coefficient (1.0), never the primary
    installation/reversal grid."""
    return (
        tuple(inputs.lambdas) == ABLATION_LAMBDAS
        and tuple(inputs.layers) == PRIMARY_LAYERS
        and inputs.vector_method == PRIMARY_VECTOR_METHOD
        and inputs.vector_normalise == PRIMARY_VECTOR_NORMALISE
        and inputs.positions == PRIMARY_POSITIONS
        and inputs.preserve_norm == PRIMARY_PRESERVE_NORM
        and inputs.max_new_tokens == PRIMARY_MAX_NEW_TOKENS
        and inputs.max_input_length == PRIMARY_MAX_INPUT_LENGTH
    )


def classify_protocol_profile(inputs: RunProfileInputs) -> str:
    """Exactly one of the five declared protocol-profile labels, or raise
    `ProtocolProfileError` if the resolved configuration is ambiguous rather than
    guess at one.

    Legacy (non-endpoint-backed) runs are always "legacy_nonconfirmatory", regardless
    of their own settings -- there is no legacy primary or secondary profile. An
    endpoint-backed run using an externally supplied vector file never matches any
    declared profile (primary_v1 requires the real manifest-backed mean direction, and
    no secondary profile is defined for an arbitrary external source), so it is
    rejected outright rather than folded into one. At most one of random-control,
    projection-ablation, or a single-layer diagnostic may be active at once. Each
    secondary profile represents exactly one deliberate deviation from the frozen
    primary protocol -- every other setting must still match it exactly, so a
    secondary label can never be used to authorize arbitrary additional drift.
    """
    if not inputs.endpoint_backed:
        return "legacy_nonconfirmatory"

    if inputs.external_vectors:
        raise ProtocolProfileError(
            "endpoint-backed runs with an externally supplied vector file (--vectors) do not "
            "match any declared protocol profile: primary_v1 requires the real manifest-backed "
            "mean direction, and no secondary profile is defined for an arbitrary external source"
        )

    active = [
        name for name, flag in (
            ("random-control", inputs.random_control),
            ("projection-ablation", inputs.mode == "ablate"),
            ("single-layer diagnostic", inputs.single_layer_override),
        ) if flag
    ]
    if len(active) > 1:
        raise ProtocolProfileError(f"ambiguous combination of secondary options: {', '.join(active)}")

    if not active:
        if _matches_frozen_primary_core(inputs):
            return "primary_v1"
        raise ProtocolProfileError(
            "endpoint-backed run does not match the frozen primary steering protocol and uses "
            "no recognized secondary-profile flag (random control, projection ablation, or a "
            "single-layer diagnostic); refusing to guess a profile"
        )

    if inputs.random_control:
        if inputs.random_seed is None or inputs.random_seed not in RANDOM_CONTROL_SEEDS:
            raise ProtocolProfileError(
                f"secondary_random_control_v1 requires --random-seed to be exactly one of "
                f"{RANDOM_CONTROL_SEEDS}, got {inputs.random_seed!r}"
            )
        if not _matches_frozen_primary_core(inputs):
            raise ProtocolProfileError(
                "secondary_random_control_v1 requires the run to otherwise preserve the frozen "
                "primary intervention settings (coefficients, layers, vector method/normalisation, "
                "positions, preserve_norm, and generation limits) -- the only permitted deviation "
                "is the random direction itself"
            )
        return "secondary_random_control_v1"

    if inputs.mode == "ablate":
        if not _matches_frozen_ablation_core(inputs):
            raise ProtocolProfileError(
                f"secondary_ablation_v1 requires lambdas={list(ABLATION_LAMBDAS)!r} (a full projection "
                "removal, not the primary installation/reversal grid), the frozen primary layer set "
                f"{list(PRIMARY_LAYERS)!r}, and otherwise the frozen primary settings (vector "
                "method/normalisation, positions, preserve_norm, and generation limits)"
            )
        return "secondary_ablation_v1"

    # single-layer diagnostic
    if len(inputs.layers) != 1 or inputs.layers[0] not in DIAGNOSTIC_LAYERS:
        raise ProtocolProfileError(
            f"secondary_layer_diagnostic_v1 requires exactly one of the predeclared diagnostic "
            f"layers {list(DIAGNOSTIC_LAYERS)!r}, got {list(inputs.layers)!r}"
        )
    if not _matches_frozen_settings_except_layers(inputs):
        raise ProtocolProfileError(
            "secondary_layer_diagnostic_v1 requires all other settings to match the frozen primary "
            "protocol (coefficients, vector method/normalisation, positions, preserve_norm, and "
            "generation limits) -- the only permitted deviation is the single diagnostic layer"
        )
    return "secondary_layer_diagnostic_v1"


def validate_random_seed_args(args: argparse.Namespace) -> None:
    """`--random-control` and `--random-seed` must be given together, exactly -- a pure
    CLI-shape check, independent of endpoint verification or protocol classification,
    so it is checked first and has no side effects of its own.

    The permitted-value check (one of RANDOM_CONTROL_SEEDS) is a protocol question and
    stays in classify_protocol_profile; this only checks the two flags travel together.
    """
    if args.random_control and args.random_seed is None:
        raise ProtocolProfileError(
            f"--random-control requires --random-seed (exactly one of {RANDOM_CONTROL_SEEDS})"
        )
    if args.random_seed is not None and not args.random_control:
        raise ProtocolProfileError("--random-seed requires --random-control")


def resolve_effective_layers(args: argparse.Namespace, cfg: "SteerSweepConfig", model_cfg: ModelConfig) -> List[int]:
    """The absolute layer indices this run will steer, computed before any vector file
    is loaded: an explicit --layers override, or the frozen last-k layers otherwise.
    Computed once, early, so protocol classification can see the resolved layer set
    before any side effect, and reused (not recomputed) once generation actually
    begins -- except when --vectors is given, which determines its own layer set from
    the loaded file and is never classified as primary_v1 (see
    classify_protocol_profile), so this placeholder value is never relied upon there.
    """
    if args.layers:
        layers = [int(x) for x in args.layers.split(",")]
        bad = [l for l in layers if not 0 <= l < model_cfg.num_layers]
        if bad:
            raise ValueError(f"layers {bad} outside 0..{model_cfg.num_layers - 1}")
        return layers
    return steered_layers(model_cfg.num_layers, cfg.layers_last_k)


def _model_loading_policy(endpoint_backed: bool) -> Dict[str, bool]:
    """The effective model/tokenizer loading policy (Tasks 012/013): endpoint-backed
    loads are restricted to verified local files with no remote code execution; legacy
    loads keep the historical, more permissive defaults unchanged."""
    if endpoint_backed:
        return {"local_files_only": True, "trust_remote_code": False}
    return {"local_files_only": False, "trust_remote_code": True}


def _construction_dir(cfg: "SteerSweepConfig", model_cfg: ModelConfig) -> Path:
    return Path(cfg.activations_dir) / model_cfg.name / "construction"


def validate_activation_artifact_for_run(
    cfg: "SteerSweepConfig", model_cfg: ModelConfig, endpoint_meta: Optional[Dict[str, Any]],
) -> activation_artifact.ActivationArtifact:
    """The verified, sidecar-bound construction-activation artifact (Task 016) for the
    endpoint pair resolved for *this* run -- required for every endpoint-backed,
    non-external-vectors run, before set_all_seeds (CUDA), output creation, metadata
    writing, logging, or any tokenizer/model/GPU access. An activations.pt from another
    pair placed beside a valid run_meta.json is rejected here even though the two files
    remain individually self-consistent, because the sidecar's endpoint fields are
    checked against the endpoint identity *this run itself resolved* -- not merely
    against what the files claim about each other.
    """
    endpoint_meta = endpoint_meta or {}
    roles = endpoint_meta.get("roles") or {}
    return activation_artifact.load_and_validate_activation_artifact(
        _construction_dir(cfg, model_cfg),
        expected_pair=endpoint_meta.get("pair"),
        expected_candidate_manifest_hash=endpoint_meta.get("candidate_manifest_hash"),
        expected_source_manifest_hash=endpoint_meta.get("source_manifest_hash"),
        expected_it_role=roles.get("it"), expected_dpo_role=roles.get("dpo"),
    )


#: Sources loaded from a frozen, manifest-backed evaluation panel via a dedicated
#: loader that takes no n/seed -- the complete panel is always used (Task 019). Kept
#: distinct from "harmfulqa", which is manifest-backed but partition-selected rather
#: than a single fixed panel.
FROZEN_SECONDARY_LOADERS = {
    "hh_rlhf": load_hh_rlhf_evaluation,
    "advbench": load_advbench_evaluation,
}

#: Every prompt_source whose records carry manifest-backed provenance (partition,
#: manifest_hash) and therefore never needs --hold-out: harmfulqa's construction and
#: evaluation partitions are already disjoint by manifest, and hh_rlhf/advbench's
#: intervention vectors and coefficients come exclusively from HarmfulQA
#: construction/calibration, never from these secondary evaluation panels themselves.
MANIFEST_BACKED_SOURCES = ("harmfulqa",) + tuple(FROZEN_SECONDARY_LOADERS)


def resolve_prompt_partition(cfg: "SteerSweepConfig", cli_partition: Optional[str]) -> Optional[str]:
    """CLI overrides YAML.

    For prompt_source == "harmfulqa" the result must be exactly "development" or
    "calibration" -- construction is direction-estimation data, and final_evaluation is
    reserved for the later confirmatory runner, not this grid search. Never falls back
    silently: an invalid or missing partition raises.

    For the frozen secondary evaluation panels (hh_rlhf, advbench; Task 019) the result
    must be exactly None: those panels are not partitioned by manifest the way
    HarmfulQA is, and a HarmfulQA partition value -- from either the YAML default or a
    CLI --partition override -- must never be silently ignored for them.
    """
    partition = cli_partition if cli_partition is not None else cfg.prompt_partition
    if cfg.prompt_source == "harmfulqa":
        if partition not in HARMFULQA_SWEEP_PARTITIONS:
            raise ValueError(
                "prompt_source='harmfulqa' requires --partition/prompt_partition to be "
                f"one of {HARMFULQA_SWEEP_PARTITIONS}; got {partition!r}"
            )
        return partition
    if cfg.prompt_source in FROZEN_SECONDARY_LOADERS:
        if partition is not None:
            raise ValueError(
                f"prompt_source={cfg.prompt_source!r} does not accept a HarmfulQA partition: "
                f"--partition/prompt_partition must be null, got {partition!r}"
            )
        return None
    return partition


def build_run_config(model_cfg: ModelConfig, cfg: "SteerSweepConfig", args: argparse.Namespace) -> Dict[str, Any]:
    """The resolved run identity for `write_run_metadata`: the model/eval dataclasses
    plus the complete parsed CLI namespace, including defaulted values, under `cli`."""
    return {"model": asdict(model_cfg), "eval": asdict(cfg), "cli": vars(args)}


def output_source_segment(prompt_source: str, partition: Optional[str]) -> Path:
    """The <prompt_source>[/<partition>] segment of the output path -- partitioned for
    HarmfulQA so development, calibration, and any historical outputs cannot resume on
    each other."""
    if prompt_source == "harmfulqa":
        return Path("harmfulqa") / partition
    return Path(prompt_source)


def reject_hold_out_for_manifest_backed_source(prompt_source: str, hold_out: int) -> None:
    """Every manifest-backed source (harmfulqa, hh_rlhf, advbench; Task 019) already
    has disjoint construction/evaluation provenance by manifest; a nonzero --hold-out
    is obsolete for all three and could misalign the frozen vector provenance."""
    if prompt_source in MANIFEST_BACKED_SOURCES and hold_out:
        raise ValueError(
            f"--hold-out must be 0 for prompt_source={prompt_source!r}: construction and "
            "evaluation partitions are already disjoint by manifest, and dropping "
            "leading construction tensors could misalign the frozen vector provenance."
        )


def load_prompts(source: str, n: int, seed: int, partition: Optional[str] = None) -> List[Dict]:
    """harmfulqa loads the named manifest partition in full. hh_rlhf/advbench load
    their complete frozen 200-record evaluation panel -- no n/seed is ever passed to
    the frozen loader, and the result is never sliced or shuffled; `n` only asserts
    that the configured `n_prompts` equals the panel's actual record count, so a
    drifted panel size fails clearly instead of silently truncating or padding.

    Each returned record is a shallow copy of the frozen loader's record with `id` set
    to `source_id` (resume/output code requires `id`), so source_id, source_index,
    prompt_hash, partition, permuted_position, and manifest_hash all survive into the
    generated JSONL via `run_one`'s own `dict(rec)` copy.
    """
    if source == "harmfulqa":
        return load_harmfulqa_partition(partition)
    if source not in FROZEN_SECONDARY_LOADERS:
        raise ValueError(f"unknown prompt_source {source!r}; use one of {sorted(FROZEN_SECONDARY_LOADERS) + ['harmfulqa']}")
    records = FROZEN_SECONDARY_LOADERS[source]()
    if len(records) != n:
        raise ValueError(
            f"prompt_source={source!r} loaded {len(records)} records from its frozen "
            f"evaluation panel, but n_prompts={n} was configured; n_prompts must equal "
            "the frozen panel's actual record count exactly -- the complete panel is "
            "always used, never a slice of it."
        )
    return [dict(r, id=r["source_id"]) for r in records]


def build_prompt_panel_metadata(source: str, records: List[Dict]) -> Dict[str, Any]:
    """Generic manifest-backed provenance for run_meta.json's extra["prompt_panel"]
    (Task 019) -- built for every manifest-backed source (harmfulqa, hh_rlhf,
    advbench).

    Every loaded panel must resolve to exactly one nonempty manifest_hash and one
    nonempty partition value across all of its records: a mixed value means two
    different manifests or partitions got concatenated somehow, and a missing value
    means the records never carried real provenance in the first place. Either failure
    mode means the provenance cannot be trusted, so this raises rather than writing
    null or ambiguous provenance into the run's metadata.
    """
    manifest_hashes = {r.get("manifest_hash") for r in records}
    partitions = {r.get("partition") for r in records}
    if len(manifest_hashes) != 1 or not next(iter(manifest_hashes)):
        raise ValueError(
            f"prompt_source={source!r}: expected exactly one nonempty manifest_hash across "
            f"all {len(records)} loaded records, got {sorted(str(h) for h in manifest_hashes)!r}"
        )
    if len(partitions) != 1 or not next(iter(partitions)):
        raise ValueError(
            f"prompt_source={source!r}: expected exactly one nonempty partition across "
            f"all {len(records)} loaded records, got {sorted(str(p) for p in partitions)!r}"
        )
    return {
        "source": source,
        "partition": next(iter(partitions)),
        "manifest_hash": next(iter(manifest_hashes)),
        "record_count": len(records),
    }


def _default_harmfulqa_manifest_path() -> Path:
    """manifests/harmfulqa_v1.json relative to the repository root, independent of the
    caller's current working directory."""
    return Path(__file__).resolve().parents[1] / "manifests" / "harmfulqa_v1.json"


def _construction_records(manifest: Dict) -> List[Dict]:
    """This manifest's construction-partition records, in ascending permuted_position --
    the exact order `layer_profile` extracted activations in."""
    return sorted(
        (e for e in manifest["records"] if e["partition"] == "construction"),
        key=lambda e: e["permuted_position"],
    )


def validate_construction_activations(blob: Dict, manifest_path: Optional[Union[str, Path]] = None) -> None:
    """Guard the vector-construction input against a legacy, mismatched, or drifted
    artifact -- checked against the frozen manifest itself, not just internal
    self-consistency.

    Delegates to `steering.activation_artifact.validate_construction_identity` (Task
    016), the single canonical implementation of this check -- reused rather than
    duplicated, since `activation_artifact`'s central sidecar validator runs the exact
    same check. Kept as a thin wrapper (name, signature, and `ValueError`-raising
    behavior all unchanged) so existing callers and tests are unaffected.
    """
    activation_artifact.validate_construction_identity(blob, manifest_path)


def pending(path: Path, records: List[Dict]) -> List[Dict]:
    """Records not already present in an output file."""
    if not path.exists():
        return records
    done = {r["id"] for r in read_jsonl(path)}
    return [r for r in records if r["id"] not in done]


def run_one(
    model, tokenizer, records, chats, coefficient, vectors, cfg, path, label, batch_size,
    mode: str = "add",
) -> int:
    """Generate for one lambda. Returns how many new records were written."""
    todo = pending(path, records)
    if not todo:
        return 0
    idx = {r["id"]: i for i, r in enumerate(records)}
    todo_chats = [chats[idx[r["id"]]] for r in todo]

    ctx = None
    if coefficient != 0.0 and vectors:
        def ctx():  # noqa: E306 -- rebuilt per batch so hooks never outlive it
            return ActivationSteering(
                model, vectors, coefficient=coefficient,
                positions=cfg.positions, preserve_norm=cfg.preserve_norm,
                mode=mode,
            )

    results = generate_batched(
        model, tokenizer, todo_chats,
        max_new_tokens=cfg.max_new_tokens,
        batch_size=batch_size,
        max_input_length=cfg.max_input_length,
        context=ctx,
        desc=label,
        return_metadata=True,
    )
    if len(results) != len(todo):
        # zip(...) would otherwise silently stop at the shorter sequence and drop the
        # remainder -- a count mismatch here means something upstream is already wrong,
        # and writing partial output would hide it.
        raise RuntimeError(
            f"generate_batched returned {len(results)} results for {len(todo)} pending "
            f"records ({label}); refusing to write a silently truncated batch"
        )

    for rec, result in zip(todo, results):
        out = dict(rec)
        if isinstance(out.get("prompt"), list):
            out["prompt_str"] = "\n".join(f"{m['role']}: {m['content']}" for m in out["prompt"])
        out["response"] = result.text
        out["generated_token_count"] = result.generated_token_count
        out["stop_reason"] = result.stop_reason
        out["stop_token_id"] = result.stop_token_id
        out["has_post_terminator_continuation"] = result.has_post_terminator_continuation
        out["lambda"] = coefficient
        append_jsonl(out, path)
    return len(todo)



def run_tag(side: str, args, extra: str = "") -> str:
    """Directory name for a run, distinguishing the vector it used.

    Generations resume by record id within their directory, so two runs that share a
    directory silently reuse each other's outputs. A learned vector and a mean-difference
    vector on the same checkpoint would otherwise collide, and the second would report the
    first's generations as its own -- which is exactly the comparison the frozen-vector
    experiment exists to make.
    """
    parts = [side, extra]
    # The vector's source is not otherwise in the path, so a run using a different
    # activations directory would land on an earlier run's generations and resume on
    # them -- reporting success while comparing a vector against itself.
    if getattr(args, "tag", None):
        parts.append("_" + args.tag)
    if getattr(args, "mode", "add") == "ablate":
        parts.append("_ablate")
    if getattr(args, "vectors", None):
        parts.append("_learned")
    if getattr(args, "layers", None):
        parts.append("_L" + args.layers.replace(",", "-"))
    if getattr(args, "hold_out", 0):
        parts.append(f"_ho{args.hold_out}")
    if getattr(args, "random_control", False):
        # The seed is part of the run's identity, not just its RNG state: five
        # controls with different seeds must land in five different directories, or
        # they collide, fail the metadata resume check, or silently reuse each
        # other's generations.
        parts.append(f"_random_s{getattr(args, 'random_seed', None)}")
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description="Generate under activation steering across lambdas.")
    parser.add_argument(
        "--model-config", default=None,
        help="Legacy YAML model-pair config. Historical/non-confirmatory use only; "
             "mutually exclusive with endpoint-backed mode below.",
    )
    parser.add_argument(
        "--endpoint-manifest", default=None,
        help="Endpoint-backed mode: candidate endpoint manifest path (protocol Section 4).",
    )
    parser.add_argument(
        "--endpoint-bundle-root", default=None,
        help="Endpoint-backed mode: root directory holding merged endpoint bundles.",
    )
    parser.add_argument(
        "--pair", choices=["A", "B"], default=None,
        help="Endpoint-backed mode: which model pair to resolve from the candidate manifest.",
    )
    parser.add_argument(
        "--endpoint-source", action="append", default=[], metavar="ARTIFACT_ID=LOCAL_ROOT",
        help="Endpoint-backed mode: repeatable, local root for one direct source artifact "
             "(e.g. pair_a_sft=/data/pair_a/SFT_merged). Not needed for a merged endpoint, "
             "which resolves entirely under --endpoint-bundle-root.",
    )
    parser.add_argument("--eval-config", required=True)
    parser.add_argument(
        "--side", choices=["it", "dpo"], required=True,
        help="it: steer the IT checkpoint with +lambda. dpo: steer the DPO checkpoint with -lambda.",
    )
    parser.add_argument(
        "--random-control", action="store_true",
        help="Replace the vectors with norm-matched random directions. If this moves "
             "behaviour as much as the real ones, the sweep measures perturbation size. "
             "Requires --random-seed.",
    )
    parser.add_argument(
        "--random-seed", type=int, default=None, metavar="SEED",
        help="Required with --random-control: the random-direction identity, exactly "
             f"one of {RANDOM_CONTROL_SEEDS} (protocol Section 8). Independent of "
             "--seed, which is the general run seed and must never double as the "
             "random-direction identity -- five controls with the same --seed but "
             "different --random-seed must resolve to five different run directories.",
    )
    parser.add_argument(
        "--mode", choices=["add", "ablate"], default="add",
        help="How the vector is applied. 'add' puts lambda*v into the stream; 'ablate' "
             "projects the component along v out, which is what the refusal-direction "
             "line does and is not a rescaling of addition.",
    )
    parser.add_argument(
        "--tag", default=None,
        help="Appended to the run directory. Use it whenever the vector comes from a "
             "different activations source, so runs cannot resume on each other.",
    )
    parser.add_argument(
        "--vectors", default=None, metavar="VECTORS.PT",
        help="Use pre-built per-layer vectors instead of deriving them from activations, "
             "e.g. one trained by train_steering_vector.py. Overrides --layers.",
    )
    parser.add_argument(
        "--layers", default=None, metavar="L[,L...]",
        help="Steer exactly these layers, overriding layers_last_k. One layer at a time "
             "is how 'why only the final layers' gets an answer rather than an assertion; "
             "a shared scalar over five of them is not equal intervention, since the "
             "displacement grows with depth.",
    )
    parser.add_argument(
        "--hold-out", type=int, default=0,
        help="Drop this many leading samples when building the vector. Use the "
             "sweep's prompt count when the vector and the evaluation come from "
             "the same corpus, so the two sets are disjoint. Must be 0 for every "
             "manifest-backed prompt_source (harmfulqa, hh_rlhf, advbench): their "
             "construction and evaluation partitions are already disjoint by manifest.",
    )
    parser.add_argument(
        "--partition", choices=sorted(VALID_HARMFULQA_PARTITIONS), default=None,
        help="HarmfulQA partition, overriding prompt_partition in the eval config. "
             "Only 'development' or 'calibration' are accepted for this grid-search "
             "script when prompt_source='harmfulqa'; rejected outright (never silently "
             "ignored) when prompt_source is 'hh_rlhf' or 'advbench'.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--sync", action="store_true")
    parser.add_argument("--hourly-rate", type=float, default=None)
    args = parser.parse_args()

    # A pure CLI-shape check (--random-control and --random-seed must travel
    # together) -- before endpoint verification even runs, since it needs nothing from
    # it and has no side effects of its own.
    validate_random_seed_args(args)

    # Endpoint verification (frozen-source binding, candidate-manifest hash/structural
    # validation, and per-file SHA-256/size streaming, for endpoint-backed mode)
    # happens here, before anything below -- including `set_all_seeds`, which touches
    # CUDA (`torch.cuda.is_available()`/`manual_seed_all`) on a GPU machine -- creates
    # output, initializes logging, or loads a prompt, vector, model, or GPU resource. A
    # mismatch has no side effects.
    model_cfg, endpoint_meta = resolve_model_source(
        model_config=args.model_config, endpoint_manifest=args.endpoint_manifest,
        endpoint_bundle_root=args.endpoint_bundle_root, pair=args.pair, endpoint_source=args.endpoint_source,
    )
    endpoint_backed = endpoint_meta is not None

    cfg = SteerSweepConfig.from_yaml(args.eval_config)

    partition = resolve_prompt_partition(cfg, args.partition)
    reject_hold_out_for_manifest_backed_source(cfg.prompt_source, args.hold_out)

    # The effective layer set, and the protocol-profile classification it feeds into,
    # are both resolved from config/CLI facts only -- before set_all_seeds (CUDA),
    # prompt loading, output creation, metadata writing, logging, checkpoint deletion,
    # model/tokenizer loading, vector loading, or generation. A profile mismatch
    # raises here, before any of that has run.
    layers = resolve_effective_layers(args, cfg, model_cfg)
    protocol_profile = classify_protocol_profile(RunProfileInputs(
        endpoint_backed=endpoint_backed,
        lambdas=tuple(cfg.lambdas), layers=tuple(layers),
        vector_method=cfg.vector_method, vector_normalise=cfg.vector_normalise,
        positions=cfg.positions, preserve_norm=cfg.preserve_norm,
        max_new_tokens=cfg.max_new_tokens, max_input_length=cfg.max_input_length,
        mode=args.mode, random_control=args.random_control, random_seed=args.random_seed,
        external_vectors=bool(args.vectors),
        single_layer_override=bool(args.layers) and len(layers) == 1,
    ))
    loading_policy = _model_loading_policy(endpoint_backed)

    # For an endpoint-backed, non-external-vectors run, the construction-activation
    # sidecar (Task 016) is required and validated against the endpoint pair resolved
    # for *this* run here -- still before set_all_seeds (CUDA), output creation,
    # metadata writing, logging, or any tokenizer/model/GPU access. (An endpoint-backed
    # run with --vectors already raised inside classify_protocol_profile above, so
    # endpoint_backed here implies not args.vectors; the check is kept explicit for
    # clarity.) Vectors are only ever built, below, from this already-validated artifact.
    activation_artifact_result = None
    if endpoint_backed and not args.vectors:
        activation_artifact_result = validate_activation_artifact_for_run(cfg, model_cfg, endpoint_meta)

    tag = run_tag(args.side, args)
    out_root = Path(cfg.output_dir) / model_cfg.name / output_source_segment(cfg.prompt_source, partition) / tag

    # Dataset binding: load prompts (and, for the manifest-backed sources, validate
    # their panel provenance) before set_all_seeds (CUDA), output/metadata mutation,
    # logging setup, or any tokenizer/model/vector loading (Task 019). Both steps here
    # are read-only -- they mutate nothing on disk -- so a malformed panel, a drifted
    # frozen-panel record count, or ambiguous/missing provenance fails here, before any
    # side effect has run.
    records = load_prompts(cfg.prompt_source, cfg.n_prompts, args.seed, partition)
    panel_meta = build_prompt_panel_metadata(cfg.prompt_source, records)

    run_meta_extra: Dict[str, Any] = {}
    if cfg.prompt_source == "harmfulqa":
        # Preserved for compatibility alongside the generic prompt_panel block below.
        run_meta_extra["harmfulqa_partition"] = partition
        run_meta_extra["harmfulqa_manifest_hash"] = panel_meta["manifest_hash"]
        run_meta_extra["harmfulqa_record_count"] = panel_meta["record_count"]
    run_meta_extra["prompt_panel"] = panel_meta
    run_meta_extra["protocol_profile"] = protocol_profile
    run_meta_extra["endpoint_backed"] = endpoint_backed
    run_meta_extra["model_loading_policy"] = loading_policy
    run_meta_extra["resolved_layers"] = layers
    run_meta_extra["random_control_seed"] = args.random_seed if args.random_control else None
    if endpoint_meta is not None:
        run_meta_extra["endpoint"] = endpoint_meta
    if activation_artifact_result is not None:
        run_meta_extra["activation_artifact"] = {
            "path": str(activation_artifact_result.acts_path),
            "sha256": activation_artifact_result.sha256,
            "size_bytes": activation_artifact_result.size_bytes,
            "run_identity_hash": activation_artifact_result.sidecar.get("run_identity_hash"),
            "endpoint": activation_artifact_result.sidecar.get("endpoint"),
        }

    # The metadata resume/mismatch check -- still before set_all_seeds (CUDA), logging,
    # model loading, or generation: a mismatched resume fails here, before it can touch
    # any of that.
    write_run_metadata(
        out_root,
        config=build_run_config(model_cfg, cfg, args),
        extra=run_meta_extra,
        argv=list(sys.argv),
    )

    set_all_seeds(args.seed)

    # Nothing above initialised the log or loaded any model/tokenizer/vectors -- a
    # mismatched resume, a malformed prompt panel, or a protocol-profile mismatch all
    # fail before this point, with no side effects.
    log = setup_logging(out_root / "steer_sweep.log")
    log.info(f"{len(records)} prompts from {cfg.prompt_source}" + (f" partition={partition}" if cfg.prompt_source == "harmfulqa" else ""))
    log.info(f"protocol_profile={protocol_profile}")

    # Vectors come from the activations for this pair, at the response readout.
    if args.vectors:
        # A vector trained under the DPO loss, rather than read off a checkpoint pair.
        # It arrives already per-layer, so the layer set comes from the file --
        # overriding the placeholder `layers` resolved above for classification
        # (protocol_profile is never primary_v1 for an external-vectors run; see
        # classify_protocol_profile).
        loaded = torch.load(Path(args.vectors), map_location="cpu")
        vectors = {int(k): v.float() for k, v in loaded.items()}
        layers = sorted(vectors)
        log.info(f"Loaded {len(vectors)} vectors from {args.vectors}; layers {layers}")
    elif activation_artifact_result is not None:
        # Already required and validated (sidecar-bound, endpoint-matched) above,
        # before set_all_seeds -- build directly from that same verified file.
        acts = activation_artifact_result.acts_path
        vectors = build_vectors(acts, method=cfg.vector_method, layers=layers,
                                normalise=cfg.vector_normalise,
                                skip_first=args.hold_out)
    else:
        # Legacy (non-endpoint-backed): unchanged behavior -- no sidecar is involved.
        acts = Path(cfg.activations_dir) / model_cfg.name / "construction" / "activations.pt"
        if not acts.exists():
            raise FileNotFoundError(f"no activations at {acts}; run layer_profile first")
        validate_construction_activations(torch.load(acts, map_location="cpu"))
        vectors = build_vectors(acts, method=cfg.vector_method, layers=layers,
                                normalise=cfg.vector_normalise,
                                skip_first=args.hold_out)
    if args.random_control:
        vectors = random_vectors_like(vectors, seed=args.random_seed)
        log.info(f"Using norm-matched RANDOM directions (control), random_seed={args.random_seed}")
    log.info(f"Steering layers {layers[0]}-{layers[-1]} with method={cfg.vector_method}")

    which = model_cfg.it_model if args.side == "it" else model_cfg.dpo_model
    sub = (model_cfg.it_subfolder if args.side == "it" else model_cfg.dpo_subfolder) or ""
    tokenizer = load_tokenizer(model_cfg.tokenizer_id or which,
                               subfolder=model_cfg.tokenizer_subfolder or sub,
                               **loading_policy)
    model = load_model(which, subfolder=sub, **loading_policy)
    chats = build_chat_prompts(tokenizer, [r["prompt"] for r in records])

    batch_size = cfg.batch_size or suggest_batch_size(model)
    log.info(f"batch size {batch_size}")

    # Ablation has no direction to reverse: removing a component is the same operation
    # whichever checkpoint it is done on, and a negative coefficient would *add* the
    # component back rather than take more of it out. Only addition takes the sign.
    sign = 1.0 if (args.side == "it" or args.mode == "ablate") else -1.0
    grid = [0.0] + [sign * abs(l) for l in cfg.lambdas]

    written = 0
    with GpuMonitor(out_root, hourly_rate=args.hourly_rate) as gpu:
        for coeff in grid:
            name = "baseline" if coeff == 0.0 else f"lambda_{coeff:+.3f}"
            path = out_root / f"{name}.jsonl"
            n = run_one(model, tokenizer, records, chats, coeff, vectors, cfg,
                        path, f"{model_cfg.name} {tag} {name}", batch_size,
                        mode=args.mode)
            written += n
            log.info(f"{name}: +{n} records -> {path}")

    log.info(f"GPU usage: {json.dumps(gpu.summary())}")
    log.info(f"{written} new generations across {len(grid)} settings")

    del model
    gc.collect()
    torch.cuda.empty_cache()

    if args.sync:
        sync_to_hub(out_root, experiment=f"steer_{cfg.prompt_source}",
                    model=f"{model_cfg.name}_{tag}")


if __name__ == "__main__":
    main()
