"""Generate under activation steering across a lambda grid.

One model, one direction, many lambdas. Positive lambda on the IT checkpoint pushes it
toward DPO behaviour; negative lambda on the DPO checkpoint pushes it back. Run the
script twice, once per side, to get both arms.

    python scripts/steer_sweep.py --model-config configs/tulu3.yaml \
        --eval-config configs/steer_sweep.yaml --side it

Writes one JSONL per lambda plus an unsteered baseline for that side. Resume is by
(lambda, prompt id): a lambda whose file already holds every prompt is skipped, and a
partial file is topped up. Scoring is a separate step -- this produces text only, so it
needs no judge server.

Note the baseline is generated by the same code path with the hooks inactive rather
than by a separate branch, so any difference between baseline and lambda=0 would be a
bug rather than a finding.
"""

from __future__ import annotations

import argparse
import gc
import json
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Union

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from steering.artifacts import GpuMonitor, sync_to_hub, write_run_metadata
from steering.config import ModelConfig
from steering.data import VALID_HARMFULQA_PARTITIONS, load_advbench, load_harmfulqa_partition, load_hh_rlhf_test
from steering.generate import build_chat_prompts, generate_batched, suggest_batch_size
from steering.models import load_model, load_tokenizer
from steering.splits import load_manifest, validate_manifest_identity
from steering.steer import ActivationSteering, build_vectors, random_vectors_like, steered_layers
from steering.utils import append_jsonl, load_yaml, read_jsonl, set_all_seeds, setup_logging

HARMFULQA_SWEEP_PARTITIONS = ("development", "calibration")


@dataclass
class SteerSweepConfig:
    """Settings for one direction of a steering sweep."""

    # Prompts
    prompt_source: str = "harmfulqa"       # harmfulqa | advbench | hh_rlhf

    # Frozen manifest partition, when prompt_source == "harmfulqa". Only "development"
    # or "calibration" are allowed here -- construction is direction-estimation data,
    # and final_evaluation is reserved for the later confirmatory runner. A CLI
    # --partition, if given, overrides this.
    prompt_partition: Optional[str] = None

    # Not consulted when prompt_source == "harmfulqa": the named partition is loaded in
    # full, with no sampling.
    n_prompts: int = 300

    # Steering strengths, given as magnitudes; the sign comes from --side.
    lambdas: Sequence[float] = field(default_factory=lambda: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

    # Which layers, counted from the top. The paper steers the last 5.
    layers_last_k: int = 5

    # Vector construction. "mean" is Eq. 2; "pc3" is what the v1 notebook ran.
    vector_method: str = "mean"
    vector_normalise: Optional[str] = None   # None | unit | relative
    positions: str = "all"                   # all | new
    preserve_norm: bool = False

    # Where the activations for vector construction live.
    activations_dir: str = "outputs/layer_profile_response_token"

    # Generation
    max_new_tokens: int = 512
    batch_size: Optional[int] = None         # None -> size from free VRAM
    max_input_length: int = 2048

    output_dir: str = "outputs/steer"

    @classmethod
    def from_yaml(cls, path: Union[str, Path]) -> "SteerSweepConfig":
        return cls(**load_yaml(path))


LOADERS = {
    "advbench": load_advbench,
    "hh_rlhf": load_hh_rlhf_test,
}


def resolve_harmfulqa_partition(cfg: "SteerSweepConfig", cli_partition: Optional[str]) -> Optional[str]:
    """CLI overrides YAML. For prompt_source == "harmfulqa" the result must be exactly
    "development" or "calibration" -- construction is direction-estimation data, and
    final_evaluation is reserved for the later confirmatory runner, not this grid
    search. Never falls back silently: an invalid or missing partition raises.
    """
    partition = cli_partition if cli_partition is not None else cfg.prompt_partition
    if cfg.prompt_source != "harmfulqa":
        return partition
    if partition not in HARMFULQA_SWEEP_PARTITIONS:
        raise ValueError(
            "prompt_source='harmfulqa' requires --partition/prompt_partition to be "
            f"one of {HARMFULQA_SWEEP_PARTITIONS}; got {partition!r}"
        )
    return partition


def build_run_config(model_cfg: ModelConfig, cfg: "SteerSweepConfig", args: argparse.Namespace) -> Dict[str, Any]:
    """The resolved run identity for `write_run_metadata`: the model/eval dataclasses
    plus the complete parsed CLI namespace, including defaulted values, under `cli`."""
    return {"model": asdict(model_cfg), "eval": asdict(cfg), "cli": vars(args)}


def output_source_segment(prompt_source: str, partition: Optional[str]) -> Path:
    """The <prompt_source>[/<partition>] segment of the output path -- partitioned for
    HarmfulQA so development, calibration, and any historical outputs cannot resume on
    each other."""
    if prompt_source == "harmfulqa":
        return Path("harmfulqa") / partition
    return Path(prompt_source)


def reject_hold_out_for_harmfulqa(prompt_source: str, hold_out: int) -> None:
    """Construction and evaluation partitions are already disjoint by manifest for
    HarmfulQA; a nonzero --hold-out is obsolete there and could misalign the frozen
    vector provenance."""
    if prompt_source == "harmfulqa" and hold_out:
        raise ValueError(
            "--hold-out must be 0 for prompt_source='harmfulqa': construction and "
            "evaluation partitions are already disjoint by manifest, and dropping "
            "leading construction tensors could misalign the frozen vector provenance."
        )


def load_prompts(source: str, n: int, seed: int, partition: Optional[str] = None) -> List[Dict]:
    if source == "harmfulqa":
        return load_harmfulqa_partition(partition)
    if source not in LOADERS:
        raise ValueError(f"unknown prompt_source {source!r}; use one of {sorted(LOADERS) + ['harmfulqa']}")
    return LOADERS[source](n=n, seed=seed)[:n]


def _default_harmfulqa_manifest_path() -> Path:
    """manifests/harmfulqa_v1.json relative to the repository root, independent of the
    caller's current working directory."""
    return Path(__file__).resolve().parents[1] / "manifests" / "harmfulqa_v1.json"


def _construction_records(manifest: Dict) -> List[Dict]:
    """This manifest's construction-partition records, in ascending permuted_position --
    the exact order `layer_profile` extracted activations in."""
    return sorted(
        (e for e in manifest["records"] if e["partition"] == "construction"),
        key=lambda e: e["permuted_position"],
    )


def validate_construction_activations(blob: Dict, manifest_path: Optional[Union[str, Path]] = None) -> None:
    """Guard the vector-construction input against a legacy, mismatched, or drifted
    artifact -- checked against the frozen manifest itself, not just internal
    self-consistency.

    `layer_profile`'s manifest-backed construction path always writes `source_ids`,
    `prompt_hashes`, `partition`, and `manifest_hash` alongside `it`/`dpo`. A tensor
    missing them is a pre-manifest (Task 002/003) artifact or came from a different
    partition. Beyond that, this loads and hash-verifies the committed manifest,
    validates its frozen identity, and requires the tensor's ordered source_ids and
    prompt_hashes to exactly match the construction partition's records -- matching
    lengths and a correct top-level manifest_hash alone would still let a corrupted,
    reordered, or drifted artifact through.
    """
    required = ("source_ids", "prompt_hashes", "partition", "manifest_hash")
    missing = [k for k in required if k not in blob]
    if missing:
        raise ValueError(
            f"activations.pt is missing {missing} -- looks like a legacy (pre-manifest) "
            "tensor with only 'it'/'dpo'; rerun layer_profile with the manifest-backed "
            "construction config"
        )
    if blob["partition"] != "construction":
        raise ValueError(f"activations.pt partition is {blob['partition']!r}, expected 'construction'")

    path = Path(manifest_path) if manifest_path is not None else _default_harmfulqa_manifest_path()
    manifest = load_manifest(path)
    validate_manifest_identity(manifest)

    if blob["manifest_hash"] != manifest["manifest_hash"]:
        raise ValueError(
            f"activations.pt manifest_hash {blob['manifest_hash']!r} does not match the "
            f"frozen manifest {manifest['manifest_hash']!r}"
        )

    construction = _construction_records(manifest)
    expected_source_ids = [e["source_id"] for e in construction]
    expected_prompt_hashes = [e["prompt_hash"] for e in construction]

    if blob["source_ids"] != expected_source_ids:
        raise ValueError(
            "activations.pt source_ids do not exactly match the construction partition's "
            "ordered source IDs -- altered, reordered, or drifted provenance"
        )
    if blob["prompt_hashes"] != expected_prompt_hashes:
        raise ValueError(
            "activations.pt prompt_hashes do not exactly match the construction partition's "
            "ordered prompt hashes -- altered, reordered, or drifted provenance"
        )

    it_shape, dpo_shape = tuple(blob["it"].shape), tuple(blob["dpo"].shape)
    if it_shape != dpo_shape:
        raise ValueError(f"activations.pt it/dpo tensor shapes differ: {it_shape} vs {dpo_shape}")

    n_prompts = it_shape[1]
    if n_prompts != len(construction):
        raise ValueError(
            f"activations.pt prompt dimension is {n_prompts}, expected {len(construction)} "
            "(the construction partition's record count)"
        )


def pending(path: Path, records: List[Dict]) -> List[Dict]:
    """Records not already present in an output file."""
    if not path.exists():
        return records
    done = {r["id"] for r in read_jsonl(path)}
    return [r for r in records if r["id"] not in done]


def run_one(
    model, tokenizer, records, chats, coefficient, vectors, cfg, path, label, batch_size,
    mode: str = "add",
) -> int:
    """Generate for one lambda. Returns how many new records were written."""
    todo = pending(path, records)
    if not todo:
        return 0
    idx = {r["id"]: i for i, r in enumerate(records)}
    todo_chats = [chats[idx[r["id"]]] for r in todo]

    ctx = None
    if coefficient != 0.0 and vectors:
        def ctx():  # noqa: E306 -- rebuilt per batch so hooks never outlive it
            return ActivationSteering(
                model, vectors, coefficient=coefficient,
                positions=cfg.positions, preserve_norm=cfg.preserve_norm,
                mode=mode,
            )

    results = generate_batched(
        model, tokenizer, todo_chats,
        max_new_tokens=cfg.max_new_tokens,
        batch_size=batch_size,
        max_input_length=cfg.max_input_length,
        context=ctx,
        desc=label,
        return_metadata=True,
    )
    if len(results) != len(todo):
        # zip(...) would otherwise silently stop at the shorter sequence and drop the
        # remainder -- a count mismatch here means something upstream is already wrong,
        # and writing partial output would hide it.
        raise RuntimeError(
            f"generate_batched returned {len(results)} results for {len(todo)} pending "
            f"records ({label}); refusing to write a silently truncated batch"
        )

    for rec, result in zip(todo, results):
        out = dict(rec)
        if isinstance(out.get("prompt"), list):
            out["prompt_str"] = "\n".join(f"{m['role']}: {m['content']}" for m in out["prompt"])
        out["response"] = result.text
        out["generated_token_count"] = result.generated_token_count
        out["stop_reason"] = result.stop_reason
        out["stop_token_id"] = result.stop_token_id
        out["lambda"] = coefficient
        append_jsonl(out, path)
    return len(todo)



def run_tag(side: str, args, extra: str = "") -> str:
    """Directory name for a run, distinguishing the vector it used.

    Generations resume by record id within their directory, so two runs that share a
    directory silently reuse each other's outputs. A learned vector and a mean-difference
    vector on the same checkpoint would otherwise collide, and the second would report the
    first's generations as its own -- which is exactly the comparison the frozen-vector
    experiment exists to make.
    """
    parts = [side, extra]
    # The vector's source is not otherwise in the path, so a run using a different
    # activations directory would land on an earlier run's generations and resume on
    # them -- reporting success while comparing a vector against itself.
    if getattr(args, "tag", None):
        parts.append("_" + args.tag)
    if getattr(args, "mode", "add") == "ablate":
        parts.append("_ablate")
    if getattr(args, "vectors", None):
        parts.append("_learned")
    if getattr(args, "layers", None):
        parts.append("_L" + args.layers.replace(",", "-"))
    if getattr(args, "hold_out", 0):
        parts.append(f"_ho{args.hold_out}")
    if getattr(args, "random_control", False):
        parts.append("_random")
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description="Generate under activation steering across lambdas.")
    parser.add_argument("--model-config", required=True)
    parser.add_argument("--eval-config", required=True)
    parser.add_argument(
        "--side", choices=["it", "dpo"], required=True,
        help="it: steer the IT checkpoint with +lambda. dpo: steer the DPO checkpoint with -lambda.",
    )
    parser.add_argument(
        "--random-control", action="store_true",
        help="Replace the vectors with norm-matched random directions. If this moves "
             "behaviour as much as the real ones, the sweep measures perturbation size.",
    )
    parser.add_argument(
        "--mode", choices=["add", "ablate"], default="add",
        help="How the vector is applied. 'add' puts lambda*v into the stream; 'ablate' "
             "projects the component along v out, which is what the refusal-direction "
             "line does and is not a rescaling of addition.",
    )
    parser.add_argument(
        "--tag", default=None,
        help="Appended to the run directory. Use it whenever the vector comes from a "
             "different activations source, so runs cannot resume on each other.",
    )
    parser.add_argument(
        "--vectors", default=None, metavar="VECTORS.PT",
        help="Use pre-built per-layer vectors instead of deriving them from activations, "
             "e.g. one trained by train_steering_vector.py. Overrides --layers.",
    )
    parser.add_argument(
        "--layers", default=None, metavar="L[,L...]",
        help="Steer exactly these layers, overriding layers_last_k. One layer at a time "
             "is how 'why only the final layers' gets an answer rather than an assertion; "
             "a shared scalar over five of them is not equal intervention, since the "
             "displacement grows with depth.",
    )
    parser.add_argument(
        "--hold-out", type=int, default=0,
        help="Drop this many leading samples when building the vector. Use the "
             "sweep's prompt count when the vector and the evaluation come from "
             "the same corpus, so the two sets are disjoint. Must be 0 for "
             "prompt_source='harmfulqa': construction and evaluation partitions are "
             "already disjoint by manifest.",
    )
    parser.add_argument(
        "--partition", choices=sorted(VALID_HARMFULQA_PARTITIONS), default=None,
        help="HarmfulQA partition, overriding prompt_partition in the eval config. "
             "Only 'development' or 'calibration' are accepted for this grid-search "
             "script when prompt_source='harmfulqa'.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--sync", action="store_true")
    parser.add_argument("--hourly-rate", type=float, default=None)
    args = parser.parse_args()

    set_all_seeds(args.seed)
    model_cfg = ModelConfig.from_yaml(args.model_config)
    cfg = SteerSweepConfig.from_yaml(args.eval_config)

    partition = resolve_harmfulqa_partition(cfg, args.partition)
    reject_hold_out_for_harmfulqa(cfg.prompt_source, args.hold_out)

    tag = run_tag(args.side, args)
    out_root = Path(cfg.output_dir) / model_cfg.name / output_source_segment(cfg.prompt_source, partition) / tag

    # Read-only preparation for the metadata identity check below -- loading prompts
    # (and, for HarmfulQA, the frozen manifest partition they came from) mutates
    # nothing on disk, so it is safe to do before the check that guards every write.
    records = load_prompts(cfg.prompt_source, cfg.n_prompts, args.seed, partition)

    run_meta_extra = None
    if cfg.prompt_source == "harmfulqa":
        manifest_hashes = {r["manifest_hash"] for r in records}
        run_meta_extra = {
            "harmfulqa_partition": partition,
            "harmfulqa_manifest_hash": next(iter(manifest_hashes)) if len(manifest_hashes) == 1 else None,
            "harmfulqa_record_count": len(records),
        }
    write_run_metadata(
        out_root,
        config=build_run_config(model_cfg, cfg, args),
        extra=run_meta_extra,
        argv=list(sys.argv),
    )

    # Nothing below may run until the identity check above has succeeded: the log is
    # not initialised and no model/tokenizer/vectors are loaded before this point -- a
    # mismatched resume fails here, before it can touch anything.
    log = setup_logging(out_root / "steer_sweep.log")
    log.info(f"{len(records)} prompts from {cfg.prompt_source}" + (f" partition={partition}" if cfg.prompt_source == "harmfulqa" else ""))

    # Vectors come from the activations for this pair, at the response readout.
    if args.vectors:
        # A vector trained under the DPO loss, rather than read off a checkpoint pair.
        # It arrives already per-layer, so the layer set comes from the file.
        loaded = torch.load(Path(args.vectors), map_location="cpu")
        vectors = {int(k): v.float() for k, v in loaded.items()}
        layers = sorted(vectors)
        log.info(f"Loaded {len(vectors)} vectors from {args.vectors}; layers {layers}")
    else:
        if args.layers:
            layers = [int(x) for x in args.layers.split(",")]
            bad = [l for l in layers if not 0 <= l < model_cfg.num_layers]
            if bad:
                parser.error(f"layers {bad} outside 0..{model_cfg.num_layers - 1}")
        else:
            layers = steered_layers(model_cfg.num_layers, cfg.layers_last_k)
        acts = Path(cfg.activations_dir) / model_cfg.name / "construction" / "activations.pt"
        if not acts.exists():
            raise FileNotFoundError(f"no activations at {acts}; run layer_profile first")
        validate_construction_activations(torch.load(acts, map_location="cpu"))
        vectors = build_vectors(acts, method=cfg.vector_method, layers=layers,
                                normalise=cfg.vector_normalise,
                                skip_first=args.hold_out)
    if args.random_control:
        vectors = random_vectors_like(vectors, seed=args.seed)
        log.info("Using norm-matched RANDOM directions (control)")
    log.info(f"Steering layers {layers[0]}-{layers[-1]} with method={cfg.vector_method}")

    which = model_cfg.it_model if args.side == "it" else model_cfg.dpo_model
    sub = (model_cfg.it_subfolder if args.side == "it" else model_cfg.dpo_subfolder) or ""
    tokenizer = load_tokenizer(model_cfg.tokenizer_id or which,
                               subfolder=model_cfg.tokenizer_subfolder or sub)
    model = load_model(which, subfolder=sub)
    chats = build_chat_prompts(tokenizer, [r["prompt"] for r in records])

    batch_size = cfg.batch_size or suggest_batch_size(model)
    log.info(f"batch size {batch_size}")

    # Ablation has no direction to reverse: removing a component is the same operation
    # whichever checkpoint it is done on, and a negative coefficient would *add* the
    # component back rather than take more of it out. Only addition takes the sign.
    sign = 1.0 if (args.side == "it" or args.mode == "ablate") else -1.0
    grid = [0.0] + [sign * abs(l) for l in cfg.lambdas]

    written = 0
    with GpuMonitor(out_root, hourly_rate=args.hourly_rate) as gpu:
        for coeff in grid:
            name = "baseline" if coeff == 0.0 else f"lambda_{coeff:+.3f}"
            path = out_root / f"{name}.jsonl"
            n = run_one(model, tokenizer, records, chats, coeff, vectors, cfg,
                        path, f"{model_cfg.name} {tag} {name}", batch_size,
                        mode=args.mode)
            written += n
            log.info(f"{name}: +{n} records -> {path}")

    log.info(f"GPU usage: {json.dumps(gpu.summary())}")
    log.info(f"{written} new generations across {len(grid)} settings")

    del model
    gc.collect()
    torch.cuda.empty_cache()

    if args.sync:
        sync_to_hub(out_root, experiment=f"steer_{cfg.prompt_source}",
                    model=f"{model_cfg.name}_{tag}")


if __name__ == "__main__":
    main()
