"""Generate under activation steering across a lambda grid.

One model, one direction, many lambdas. Positive lambda on the IT checkpoint pushes it
toward DPO behaviour; negative lambda on the DPO checkpoint pushes it back. Run the
script twice, once per side, to get both arms.

    python scripts/steer_sweep.py --model-config configs/tulu3.yaml \
        --eval-config configs/steer_sweep.yaml --side it

Writes one JSONL per lambda plus an unsteered baseline for that side. Resume is by
(lambda, prompt id): a lambda whose file already holds every prompt is skipped, and a
partial file is topped up. Scoring is a separate step -- this produces text only, so it
needs no judge server.

Note the baseline is generated by the same code path with the hooks inactive rather
than by a separate branch, so any difference between baseline and lambda=0 would be a
bug rather than a finding.
"""

from __future__ import annotations

import argparse
import gc
import json
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Union

import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from steering.artifacts import GpuMonitor, sync_to_hub, write_run_metadata
from steering.config import ModelConfig
from steering.data import load_advbench, load_harmfulqa, load_hh_rlhf_test
from steering.generate import build_chat_prompts, generate_batched, suggest_batch_size
from steering.models import load_model, load_tokenizer
from steering.steer import ActivationSteering, build_vectors, random_vectors_like, steered_layers
from steering.utils import append_jsonl, load_yaml, read_jsonl, set_all_seeds, setup_logging


@dataclass
class SteerSweepConfig:
    """Settings for one direction of a steering sweep."""

    # Prompts
    prompt_source: str = "harmfulqa"       # harmfulqa | advbench | hh_rlhf
    n_prompts: int = 300

    # Steering strengths, given as magnitudes; the sign comes from --side.
    lambdas: Sequence[float] = field(default_factory=lambda: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6])

    # Which layers, counted from the top. The paper steers the last 5.
    layers_last_k: int = 5

    # Vector construction. "mean" is Eq. 2; "pc3" is what the v1 notebook ran.
    vector_method: str = "mean"
    vector_normalise: Optional[str] = None   # None | unit | relative
    positions: str = "all"                   # all | new
    preserve_norm: bool = False

    # Where the activations for vector construction live.
    activations_dir: str = "outputs/layer_profile_response_token"

    # Generation
    max_new_tokens: int = 512
    batch_size: Optional[int] = None         # None -> size from free VRAM
    max_input_length: int = 2048

    output_dir: str = "outputs/steer"

    @classmethod
    def from_yaml(cls, path: Union[str, Path]) -> "SteerSweepConfig":
        return cls(**load_yaml(path))


LOADERS = {
    "harmfulqa": load_harmfulqa,
    "advbench": load_advbench,
    "hh_rlhf": load_hh_rlhf_test,
}


def load_prompts(source: str, n: int, seed: int) -> List[Dict]:
    if source not in LOADERS:
        raise ValueError(f"unknown prompt_source {source!r}; use one of {sorted(LOADERS)}")
    return LOADERS[source](n=n, seed=seed)[:n]


def pending(path: Path, records: List[Dict]) -> List[Dict]:
    """Records not already present in an output file."""
    if not path.exists():
        return records
    done = {r["id"] for r in read_jsonl(path)}
    return [r for r in records if r["id"] not in done]


def run_one(
    model, tokenizer, records, chats, coefficient, vectors, cfg, path, label, batch_size
) -> int:
    """Generate for one lambda. Returns how many new records were written."""
    todo = pending(path, records)
    if not todo:
        return 0
    idx = {r["id"]: i for i, r in enumerate(records)}
    todo_chats = [chats[idx[r["id"]]] for r in todo]

    ctx = None
    if coefficient != 0.0 and vectors:
        def ctx():  # noqa: E306 -- rebuilt per batch so hooks never outlive it
            return ActivationSteering(
                model, vectors, coefficient=coefficient,
                positions=cfg.positions, preserve_norm=cfg.preserve_norm,
            )

    texts = generate_batched(
        model, tokenizer, todo_chats,
        max_new_tokens=cfg.max_new_tokens,
        batch_size=batch_size,
        max_input_length=cfg.max_input_length,
        context=ctx,
        desc=label,
    )

    for rec, text in zip(todo, texts):
        out = dict(rec)
        if isinstance(out.get("prompt"), list):
            out["prompt_str"] = "\n".join(f"{m['role']}: {m['content']}" for m in out["prompt"])
        out["response"] = text
        out["lambda"] = coefficient
        append_jsonl(out, path)
    return len(todo)



def run_tag(side: str, args, extra: str = "") -> str:
    """Directory name for a run, distinguishing the vector it used.

    Generations resume by record id within their directory, so two runs that share a
    directory silently reuse each other's outputs. A learned vector and a mean-difference
    vector on the same checkpoint would otherwise collide, and the second would report the
    first's generations as its own -- which is exactly the comparison the frozen-vector
    experiment exists to make.
    """
    parts = [side, extra]
    if getattr(args, "vectors", None):
        parts.append("_learned")
    if getattr(args, "layers", None):
        parts.append("_L" + args.layers.replace(",", "-"))
    if getattr(args, "hold_out", 0):
        parts.append(f"_ho{args.hold_out}")
    if getattr(args, "random_control", False):
        parts.append("_random")
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description="Generate under activation steering across lambdas.")
    parser.add_argument("--model-config", required=True)
    parser.add_argument("--eval-config", required=True)
    parser.add_argument(
        "--side", choices=["it", "dpo"], required=True,
        help="it: steer the IT checkpoint with +lambda. dpo: steer the DPO checkpoint with -lambda.",
    )
    parser.add_argument(
        "--random-control", action="store_true",
        help="Replace the vectors with norm-matched random directions. If this moves "
             "behaviour as much as the real ones, the sweep measures perturbation size.",
    )
    parser.add_argument(
        "--vectors", default=None, metavar="VECTORS.PT",
        help="Use pre-built per-layer vectors instead of deriving them from activations, "
             "e.g. one trained by train_steering_vector.py. Overrides --layers.",
    )
    parser.add_argument(
        "--layers", default=None, metavar="L[,L...]",
        help="Steer exactly these layers, overriding layers_last_k. One layer at a time "
             "is how 'why only the final layers' gets an answer rather than an assertion; "
             "a shared scalar over five of them is not equal intervention, since the "
             "displacement grows with depth.",
    )
    parser.add_argument(
        "--hold-out", type=int, default=0,
        help="Drop this many leading samples when building the vector. Use the "
             "sweep's prompt count when the vector and the evaluation come from "
             "the same corpus, so the two sets are disjoint.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--sync", action="store_true")
    parser.add_argument("--hourly-rate", type=float, default=None)
    args = parser.parse_args()

    set_all_seeds(args.seed)
    model_cfg = ModelConfig.from_yaml(args.model_config)
    cfg = SteerSweepConfig.from_yaml(args.eval_config)

    tag = run_tag(args.side, args)
    out_root = Path(cfg.output_dir) / model_cfg.name / cfg.prompt_source / tag
    out_root.mkdir(parents=True, exist_ok=True)
    log = setup_logging(out_root / "steer_sweep.log")
    write_run_metadata(out_root, config={
        "model": asdict(model_cfg), "eval": asdict(cfg),
        "side": args.side, "random_control": args.random_control, "seed": args.seed,
    })

    records = load_prompts(cfg.prompt_source, cfg.n_prompts, args.seed)
    log.info(f"{len(records)} prompts from {cfg.prompt_source}")

    # Vectors come from the activations for this pair, at the response readout.
    if args.vectors:
        # A vector trained under the DPO loss, rather than read off a checkpoint pair.
        # It arrives already per-layer, so the layer set comes from the file.
        loaded = torch.load(Path(args.vectors), map_location="cpu")
        vectors = {int(k): v.float() for k, v in loaded.items()}
        layers = sorted(vectors)
        log.info(f"Loaded {len(vectors)} vectors from {args.vectors}; layers {layers}")
    else:
        if args.layers:
            layers = [int(x) for x in args.layers.split(",")]
            bad = [l for l in layers if not 0 <= l < model_cfg.num_layers]
            if bad:
                parser.error(f"layers {bad} outside 0..{model_cfg.num_layers - 1}")
        else:
            layers = steered_layers(model_cfg.num_layers, cfg.layers_last_k)
        acts = Path(cfg.activations_dir) / model_cfg.name / "activations.pt"
        if not acts.exists():
            raise FileNotFoundError(f"no activations at {acts}; run layer_profile first")
        vectors = build_vectors(acts, method=cfg.vector_method, layers=layers,
                                normalise=cfg.vector_normalise,
                                skip_first=args.hold_out)
    if args.random_control:
        vectors = random_vectors_like(vectors, seed=args.seed)
        log.info("Using norm-matched RANDOM directions (control)")
    log.info(f"Steering layers {layers[0]}-{layers[-1]} with method={cfg.vector_method}")

    which = model_cfg.it_model if args.side == "it" else model_cfg.dpo_model
    sub = (model_cfg.it_subfolder if args.side == "it" else model_cfg.dpo_subfolder) or ""
    tokenizer = load_tokenizer(model_cfg.tokenizer_id or which,
                               subfolder=model_cfg.tokenizer_subfolder or sub)
    model = load_model(which, subfolder=sub)
    chats = build_chat_prompts(tokenizer, [r["prompt"] for r in records])

    batch_size = cfg.batch_size or suggest_batch_size(model)
    log.info(f"batch size {batch_size}")

    sign = 1.0 if args.side == "it" else -1.0
    grid = [0.0] + [sign * abs(l) for l in cfg.lambdas]

    written = 0
    with GpuMonitor(out_root, hourly_rate=args.hourly_rate) as gpu:
        for coeff in grid:
            name = "baseline" if coeff == 0.0 else f"lambda_{coeff:+.3f}"
            path = out_root / f"{name}.jsonl"
            n = run_one(model, tokenizer, records, chats, coeff, vectors, cfg,
                        path, f"{model_cfg.name} {tag} {name}", batch_size)
            written += n
            log.info(f"{name}: +{n} records -> {path}")

    log.info(f"GPU usage: {json.dumps(gpu.summary())}")
    log.info(f"{written} new generations across {len(grid)} settings")

    del model
    gc.collect()
    torch.cuda.empty_cache()

    if args.sync:
        sync_to_hub(out_root, experiment=f"steer_{cfg.prompt_source}",
                    model=f"{model_cfg.name}_{tag}")


if __name__ == "__main__":
    main()
